version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    open-pull-requests-limit: 2
    cooldown:
      default-days: 3
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 2
    cooldown:
      default-days: 3
    groups:
      workflows:
        applies-to: version-updates
        patterns:
          - '*'
    schedule:
      interval: "weekly"
      day: "wednesday"
