[package]
name = "svix-ksuid"
version = "0.8.0"
authors = ["Svix Inc. <oss@svix.com>"]
edition = "2024"
rust-version = "1.88"
description="A pure Rust and fully tested KSUID implementation"
homepage="https://www.svix.com"
repository="https://github.com/svix/rust-ksuid"
readme="README.md"
license="MIT"
keywords=["ksuid", "uuid", "svix", "segment"]
categories = ["data-structures", "concurrency", "database", "encoding"]

[features]
# Include `time` by default, to match old behavior
default = ["time03"]
serde = ["dep:serde"]
jiff02 = ["dep:jiff"]
time03 = ["dep:time"]
chrono04 = ["dep:chrono"]

[dependencies]
base-encode = "^0.3.1"
byteorder = "^1.4.3"
chrono = { version = "0.4", optional = true }
getrandom = "0.4.2"
jiff = { version = "0.2", optional = true }
serde = { version = "^1.0.145", optional = true, features = ["derive"] }
time = { version = "0.3.47", optional = true }

[dev-dependencies]
serde = { version = "^1.0.145", features = ["derive"] }
serde_json = "^1.0.85"

[badges]
maintenance = {status="actively-developed"}
