name: Rust CI
on:
  workflow_call:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy, rustfmt
      - uses: taiki-e/install-action@213ccc1a076163c093f914550b94feb90fab916d # v2.79.2
        with:
          tool: cargo-sort
      - uses: taiki-e/install-action@213ccc1a076163c093f914550b94feb90fab916d # v2.79.2
        with:
          tool: cargo-machete
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: clippy
        run: cargo clippy --all --all-targets --all-features
      - name: rustfmt
        run: cargo fmt --all -- --check
      - name: cargo-sort
        run: cargo sort --check --no-format -o package,lib,bin,features,dependencies,dev-dependencies,lints,workspace
      - name: cargo-machete
        run: cargo machete
  test-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.88.0", stable, beta]
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Run tests (all features)
        run: cargo test --all --all-features --all-targets
      - name: Run tests (no features)
        run: cargo test --all --no-default-features --all-targets
      - name: Run doc tests
        run: cargo test --doc
      - name: Run tests (jiff02)
        run: cargo test --all --no-default-features --features "jiff02" --all-targets
      - name: Run tests (chrono04)
        run: cargo test --all --no-default-features --features "chrono04" --all-targets
      - name: Run tests (time03)
        run: cargo test --all --no-default-features --features "time03" --all-targets
  prek:
    name: Validate prek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - uses: j178/prek-action@0bb87d7f00b0c99306c8bcb8b8beba1eb581c037 # v1.1.1
  cargo-deny:
    name: cargo-deny check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: EmbarkStudios/cargo-deny-action@a531616d8ce3b9177443e48a1159bc945a099823 # v2.0.19
        with:
          manifest-path: Cargo.toml
