name: Rust CI
on:
  workflow_call:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy, rustfmt
      - uses: taiki-e/install-action@9e1e5806d4a4822de933115878265be9aaa786d9 # v2.82.2
        with:
          tool: cargo-sort
      - uses: taiki-e/install-action@9e1e5806d4a4822de933115878265be9aaa786d9 # v2.82.2
        with:
          tool: cargo-machete
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: clippy
        run: cargo clippy --all --all-targets --all-features
      - name: rustfmt
        run: cargo fmt --all -- --check
      - name: cargo-sort
        run: cargo sort --check --no-format -o package,lib,bin,features,dependencies,dev-dependencies,lints,workspace
      - name: cargo-machete
        run: cargo machete
  test-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.88.0", stable, beta]
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537 # master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Run tests (all features)
        run: cargo test --all --all-features --all-targets
      - name: Run tests (no features)
        run: cargo test --all --no-default-features --all-targets
      - name: Run doc tests
        run: cargo test --doc
      - name: Run tests (jiff02)
        run: cargo test --all --no-default-features --features "jiff02" --all-targets
      - name: Run tests (chrono04)
        run: cargo test --all --no-default-features --features "chrono04" --all-targets
      - name: Run tests (time03)
        run: cargo test --all --no-default-features --features "time03" --all-targets
  prek:
    name: Validate prek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # v2.0.4
  cargo-deny:
    name: cargo-deny check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: EmbarkStudios/cargo-deny-action@bb137d7af7e4fb67e5f82a49c4fce4fad40782fe # v2.0.20
        with:
          manifest-path: Cargo.toml
