name: CI
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v1
      - name: clippy
        run: cargo clippy --all --all-targets --all-features
      - name: rustfmt
        run: cargo fmt --all -- --check
  test-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.88.0", stable, beta]
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - name: Run tests (all features)
        run: cargo test --all --all-features --all-targets
      - name: Run tests (no features)
        run: cargo test --all --no-default-features --all-targets
      - name: Run doc tests
        run: cargo test --doc
