name: Rust CI
on:
  workflow_call:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy, rustfmt
      - uses: taiki-e/install-action@7f4eb899022d8fe70b20c4f3de697aa85c309026 # v2.85.11
        with:
          tool: cargo-sort
      - uses: taiki-e/install-action@7f4eb899022d8fe70b20c4f3de697aa85c309026 # v2.85.11
        with:
          tool: cargo-machete
      - uses: Swatinem/rust-cache@a45951ff880207c249adf57334cf2e9bd81d6e1e # v2
      - name: clippy
        run: cargo clippy --all --all-targets --all-features
      - name: rustfmt
        run: cargo fmt --all -- --check
      - name: cargo-sort
        run: cargo sort --check --no-format -o package,lib,bin,features,dependencies,dev-dependencies,lints,workspace
      - name: cargo-machete
        run: cargo machete
  test-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.88.0", stable, beta]
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@a45951ff880207c249adf57334cf2e9bd81d6e1e # v2
      - name: Run tests (all features)
        run: cargo test --all --all-features --all-targets
      - name: Run tests (no features)
        run: cargo test --all --no-default-features --all-targets
      - name: Run doc tests
        run: cargo test --doc
      - name: Run tests (jiff02)
        run: cargo test --all --no-default-features --features "jiff02" --all-targets
      - name: Run tests (chrono04)
        run: cargo test --all --no-default-features --features "chrono04" --all-targets
      - name: Run tests (time03)
        run: cargo test --all --no-default-features --features "time03" --all-targets
  prek:
    name: Validate prek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
  cargo-deny:
    name: cargo-deny check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25 # v2.1.1
        with:
          manifest-path: Cargo.toml
